 
 --h2Datebase;

create table COUNTRY 
 (id integer generated by default as identity, 
 countryName varchar(255),
 population bigint,
 primary key (id))
 
-- <beans:bean id="dataSource"
--		class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
--		<beans:property name="driverClassName"
--			value="org.h2.Driver" />
--		<beans:property name="url"
--			value="jdbc:h2:tcp://localhost/~/test" />
--		<beans:property name="username" value="sa" />
--		<beans:property name="password" value="" />
--	</beans:bean>
<props>
				<prop key="hibernate.dialect">org.hibernate.dialect.H2Dialect </prop>
				
				<prop key="hibernate.show_sql">true</prop>
				<prop key="hibernate.hbm2ddl.auto">update</prop>

			</props>
 
 	
 
 
 --mysql Properties:
 
 
 --Db Properties mysql
# MySQL properties
mysql.driver=com.mysql.jdbc.Driver
mysql.url=jdbc:mysql://localhost:3306/filedb?useSSL=false
mysql.user=root
mysql.password=root

# Hibernate properties
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update

#C3P0 properties
hibernate.c3p0.min_size=5
hibernate.c3p0.max_size=20
hibernate.c3p0.acquire_increment=1
hibernate.c3p0.timeout=1800
hibernate.c3p0.max_statements=150


beans:bean id="dataSource"
	class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
	<beans:property name="driverClassName"
		value="com.mysql.jdbc.Driver" />
	<beans:property name="url"
		value="jdbc:mysql://localhost:3306/filedb?useSSL=false" />
	<beans:property name="username" value="root" />
	<beans:property name="password" value="root" />
	</beans:bean>
<props>
				<!-- <prop key="hibernate.dialect">org.hibernate.dialect.H2Dialect -->
				 <prop key="hibernate.dialect">org.hibernate.dialect.MySQLDialect 
				</prop>
				<prop key="hibernate.show_sql">true</prop>
				<prop key="hibernate.hbm2ddl.auto">update</prop>

			</props>
